name: Auto Lint Auto Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 and autopep8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # automatically fix some linting issues using autopep8
        autopep8 --in-place --recursive .
    - name: Test with pytest
      run: |
        pytest
    - name: Commit suggested changes
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git config --global user.name "AUTO CI Workflow"
        git config --global user.email "ci-worksflow@github.com"
        git add .
        git commit -m "Auto-fix linting issues"
        git push origin ${{ github.head_ref }}
